replicaCount: 1
frontend:
  image:
    repository: anthonygilbertt/vue-book-tracker-frontend
    pullPolicy: Always
    tag: e99e0b
  service:
    type: ClusterIP
    port: 80
    targetPort: 5001
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
backend:
  image:
    repository: anthonygilbertt/vue-book-tracker-backend
    pullPolicy: Always
    tag: e99e0b
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8083
    name: http
  env:
    PORT: "8083"
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: booktracker.dev
      paths:
        - path: /api/
          pathType: Prefix
          service: backend
        - path: /
          pathType: Prefix
          service: frontend
  tls:
    - secretName: book-tracker-tls
      hosts:
        - booktracker.dev
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
