redis-ha:
  enabled: false
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 2

controller:
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

server:
  replicas: 1
  autoscaling:
    enabled: false
    maxReplicas: 2
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - argocd.booktracker.dev
    tls:
      - hosts:
        - argocd.booktracker.dev
        secretName: argocd-server-tls

repoServer:
  replicas: 1
  autoscaling:
    enabled: false
    maxReplicas: 2
  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 150m
      memory: 256Mi

applicationSet:
  replicas: 1
  autoscaling:
    enabled: false
    maxReplicas: 2
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

redis:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

notifications:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

dex:
  resources:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 25m
      memory: 32Mi

global:
  domain: argocd.booktracker.dev

configs:
  params:
    # Run in insecure mode behind nginx SSL termination
    server.insecure: true
  cm:
    # Set the external URL
    url: "https://argocd.booktracker.dev"

certificate:
  enabled: true
