redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  replicas: 1
  ingress:
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls.passthrough: "true"
    enabled: true
    ingressClassName: traefik
    tls: true

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd.booktracker.dev

certificate:
  enabled: true