apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  namespace: github-runners
  labels:
    app: github-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: runner
        image: summerwind/actions-runner:latest
        env:
        - name: RUNNER_NAME
          value: "k8s-lightweight-runner"
        - name: RUNNER_REPO
          value: "anthony-gilbert/Vue-Book-Tracker"
        - name: RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-runner-token
              key: token
        - name: RUNNER_WORKDIR
          value: "/tmp/runner"
        - name: DISABLE_RUNNER_UPDATE
          value: "true"
        - name: RUNNER_LABELS
          value: "kubernetes,self-hosted,vue-book-tracker"
        - name: RUNNER_ALLOW_RUNASROOT
          value: "1"
        - name: DEBIAN_FRONTEND
          value: noninteractive
        - name: RUNNER_REPLACE_EXISTING
          value: "true"
        volumeMounts:
        - name: runner-workdir
          mountPath: /tmp/runner
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep Runner.Listener || exit 1"
          initialDelaySeconds: 90
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: runner-workdir
        emptyDir:
          sizeLimit: "500Mi"
      restartPolicy: Always
