apiVersion: v1
kind: Secret
metadata:
  name: github-runner-token
  namespace: github-runners
type: Opaque
data:
  # This will be populated by the setup script
  # The token should be base64 encoded
  token: ""
